remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Cassie Maz's Personal Website
description: ["Welcome to my personal website! Explore to learn about my research interests, my completed and ongoing projects, and what I do when not drowning in academia!"]
