theme: jekyll-theme-minimal
title: Cassie Maz's Personal Website
description: [Welcome to my personal website! Explore to learn about my research interests\, my completed and ongoing projects\, and what I do when not drowning in academia!]
